name = "Library"
uuid = "7ea7381d-357e-4dbe-a6c3-b3cc440ba0c3"
authors = ["Akhil <akhilnandangate2019@gmail.com>"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
ModelingToolkit = "10.25.0"
ModelingToolkitStandardLibrary = "2.25.0"
OrdinaryDiffEq = "6.102.1"
